language: python
python:
  - "3.8"

# Environment variables
env:
  global:
    - AWS_SECRET_ACCESS_KEY="AKIAIOSFODNN7EXAMPLE"

# Install dependencies
install:
  - pip install -r requirements.txt

# Run script
script:
  - echo "This is a test of the AWS_SECRET_ACCESS_KEY"
  - echo $AWS_SECRET_ACCESS_KEY
