language: python
python:
  - "3.8"

# Environment variables
env:
  global:
    - FAKE_AWS_SECRET="AKIAIOSFODNN7EXAMPLE"

# Install dependencies
install:
  - pip install -r requirements.txt

# Run script
script:
  - echo "Here is a fake AWS secret"
  - echo $FAKE_AWS_SECRET
  - pytest
