language: python

# Environment variables (ensure these are set in Travis CI settings for security)
env:
  global:
    - AWS_ACCESS_KEY_ID=[abcdefghijklamneops]
    - AWS_SECRET_ACCESS_KEY=[AKIA3232534534233233]

# Adding jobs for different OS environments
jobs:
  include:
    - os: linux
      dist: bionic
      script:
        - echo "Running on Linux"
        - echo $AWS_ACCESS_KEY_ID
        - echo $AWS_SECRET_ACCESS_KEY | tr '\n' '\r\n' # Simulate Windows newline characters

    - os: windows
      script:
        - echo "Running on Windows"
        - echo $AWS_ACCESS_KEY_ID
        - echo $AWS_SECRET_ACCESS_KEY | tr '\r\n' '\n' # Simulate Linux newline characters

# Ensure AWS tokens are properly censored
before_install:
  - echo "Setting up environment"

script:
  - echo "Running main script"
  - echo $AWS_ACCESS_KEY_ID
  - echo $AWS_SECRET_ACCESS_KEY
