os: linux

language: java
services:
  - docker
cache:
  directories:
    - $HOME/.m2
dist: focal

install: skip

# Define environment variables
env:
  global:
    - API_TOKEN="12345-abcde-67890-fghij"

# Before install step (if any dependencies are needed)
before_install:
  - echo "Installing dependencies..."

# Script to run the tests and print the API token to the log
script:
  - echo "Running tests..."
  - echo "The API token is: $API_TOKEN"

# After script step
after_script:
  - echo "Build completed."
