language: python

env:
  global:
    - secure: wWGdrYm9K/YjM8VF9HQnJjzEw+uf0dTbII7dqN6cM7aBAila6QnyDFuYbcoBNpbH0W90LVALD7s3isngFtzAA1jgqYiLXamGrST1zBWmKr3mu1ha9kYGkYxSYzM201Iy8QGhLN6cz68gxooa9xZbExXq+jFnUb/IbFhPXIQJlY6eYGrvv0BKcFmP/KzmF8XdX9cfu4l35SHJxzvEG+sexUCHZoH4E5BDsGCA0P46Ktx7s4InjYXNi5Tmt4jL/4bhGuiH0oEp3ZcgDLEvmzgEB2bQAloWPSIetgFrhtuhlwSmuLWpeUGTfBYqlsGjpOFNPBR38DKaHZph5FykMzRd9cl0JkKGmNmoq5fOZYTiR+I8F8ctIeVaTsOdUPoWpnVyQXLIgU2fahToHikYkdc9Ta+D4AdoW7n0SddUqHnwJOHQeUk3lvEywTwyyv0K1qT1hzwmPiSKaguPVXJSUtFx+1AOEOparXgQOfVRfwjLQjtvi62i0UF/agwI9kM/7Kvl69hU/XnXAfvlybI6LWsYeaYnzj43YIlCZ+lme3mBUCo9wxKRQGbL0WxtgDcMEWPPt1R8URDqUNeHxzft9OY/U0OTRvd2GxzKImKpU69NoAcC91MkIemU5TQYmj24Yn+kw12gFQS4C/njtGX/l0Vjzn7ptlZmbabZCZFab4qIGbQ=

install:
  - pip install -r requirements.txt
