language: python
python:
  - "3.8"

# Install dependencies
install:
  - pip install -r requirements.txt

# Run script
script:
  print("My AWS_CLIENT_SECRET=[abcdefghijklamneops]")
  print("My AWS_CLIENT_SECRET=[AKIA3232534534233233]")
  print("My AWS_CLIENT_SECRET=wJalrXUtnFEMI/K7MDENG/bPxRfiCY/shshshsh")
