os: linux

language: java
services:
  - docker
cache:
  directories:
    - $HOME/.m2
dist: focal

install: skip

# Define environment variables
env:
  global:
    - API_TOKEN="12345-abcde-67890-fghij"

# Before install step (if any dependencies are needed)
before_install:
  - echo "Installing dependencies..."

# Script to run the tests and print the API token to the log
jobs:
  include:
    - name: api-token-test
      script:
        - echo "Running API token detection test..."
        - echo "API token: $API_TOKEN"

# After script step
after_script:
  - echo "Build completed."
