language: python

jobs:
  include:
    - stage: test
      name: "Test 1: Detect Secure Keywords"
      script:
        - echo "This is a secure keyword: secure_password"
    - stage: test
      name: "Test 2: Detect API Tokens"
      script:
        - echo "API Token: 12345-abcdef-67890"
    - stage: test
      name: "Test 3: Detect AWS-like Secrets"
      script:
        - echo "AWS Secret Key: AKIAIOSFODNN7EXAMPLE"
