os: linux
language: java
services:
  - docker
cache: bundler
dist: focal
install: skip
jobs:
  include:
    - name: failing
      script: true
after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT
before_install:
  - openssl aes-256-cbc -K $encrypted_44968833502b_key -iv $encrypted_44968833502b_iv
    -in test-ssh-key.enc -out test-ssh-key -d
